#!/bin/sh

if [ $(id -u) != "0" ]; then
    echo "Co loi: Ban phai dang nhap bang user root!"
    exit
fi

if [ -f /var/cpanel/cpanel.config ]; then
echo "Server cua ban da cai san WHM/Cpanel, neu ban muon dung APT MEDIA"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/psa/.psa.shadow ]; then
echo "Server cua ban da cai san Plesk, neu ban muon dung APT MEDIA"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/init.d/directadmin ]; then
echo "Server cua ban da cai san DirectAdmin, neu ban muon dung APT MEDIA"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/init.d/webmin ]; then
echo "Server cua ban da cai san webmin, neu ban muon dung APT MEDIA"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /home/vpssim.conf ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Server/VPS cua ban da cai san APT MEDIA"
echo "Hay su dung lenh APT MEDIA de truy cap APT MEDIA menu"
echo "Chao tam biet !"
echo "========================================================================="
echo "========================================================================="
rm -rf install*
exit
fi

arch=`uname -m`
if [ ! "$arch" = "x86_64" ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Hien tai! APT MEDIA chi ho tro phien ban x64 bit"
echo "Vui long cai dat phien ban he dieu hanh x86_64 roi thu lai"
echo "Chao tam biet !"
echo "========================================================================="
echo "========================================================================="
rm -rf install*
exit
fi

if [ -f /etc/yum.repos.d/epel.repo ]; then
sudo sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
fi

yes | cp -rf /opt/apt_media/script/vpssim/calc /bin/calc && chmod +x /bin/calc
clear  
rm -rf /root/vpssim*

echo "========================================================================="
echo "APT MEDIA Ho Tro Centos 6 & Centos 7 & Centos 8 x64"
echo "-------------------------------------------------------------------------"
echo "Ban nen su dung Centos 7 x64 de Server co hieu suat tot nhat."
echo "-------------------------------------------------------------------------"

echo "========================================================================="

yourlanguage="vietnamese"

current_os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))


cd ~

if [ "$yourlanguage" = "english" ]; then
echo "----------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
cd /opt/apt_media/script/vpssim/centos${current_os_version} ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
yes | cp -rf /opt/apt_media/script/vpssim/centos${current_os_version}/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
elif [ "$yourlanguage" = "vietnamese" ]; then
echo "----------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
if [ "$current_os_version" == "6" ]; then
yes | cp -rf /opt/apt_media/script/vpssim/centos6/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
elif [ "$current_os_version" == "7" ]; then
yes | cp -rf /opt/apt_media/script/vpssim/centos7/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
else
yes | cp -rf /opt/apt_media/script/vpssim/centos8/vpssim-setup ~/vpssim-setup ; chmod +x vpssim-setup ; clear ; bash vpssim-setup
fi
else 
rm -rf /root/install* && rm -rf /root/vpssim* && clear
fi