#!/bin/sh

echo "-------------------------------------------------------------------------"
echo "Ok ! please wait check reset code from git..."

cd ~
if [ -d /opt/apt_media ]; then
rm -rf /opt/apt_media/*
rm -rf /opt/apt_media
sleep 5
fi

/etc/vpssim/menu/git-clone
sleep 1

clear
echo "========================================================================="
echo "Done! Reset code from git..."
/etc/vpssim/menu/vpssim-update-upgrade-service-menu
